name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute deploy script
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "cd ${{ vars.DEPLOY_DIR }} && bash deploy.sh"